# Generated by Django 4.2.11 on 2024-03-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_date_event_event_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='distance',
            field=models.CharField(default='0km', max_length=20),
            preserve_default=False,
        ),
    ]
